import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./_components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Hugolf",
//   description: "Generated by create next app",
// };

export const metadata = {
  title: {
    default: "Hugolf",
    template: "%s | Hugolf",
  },
  // icons: {
  //   icon: "/favicon.ico",
  //   shortcut: "/favicon.ico",
  //   apple: "/apple-touch-icon.png",
  //   other: {
  //     rel: "mask-icon",
  //     url: "/favicon.svg",
  //   },
  // },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geistMono.className}>
        <header>
          <Navigation />
        </header>

        <main>{children}</main>
        {/* <footer>footer</footer> */}
      </body>
    </html>
  );
}
